name: CI

on:
  push:
    braches: [ 1.x ]
  pull_request:
    branches: [ 1.x ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: build_dir
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
          check-latest: true
      - name: Gradle Check
        run: |
          cd $GITHUB_WORKSPACE/build_dir
          ./gradlew check
      - name: Jacoco Test
        run: |
          cd $GITHUB_WORKSPACE/build_dir
          ./gradlew jacocoTestReport
      - name: Codecov
        uses: codecov/codecov-action@v1

